version: '3'

services:
    micro-counter-proxy:
        build: ./MicroCounter.Proxy
        ports:
            - 80:80
            - 443:443
        depends_on:
            - micro-counter-web
            - micro-counter-api
    micro-counter-web:
        build: ./MicroCounter.Web
        depends_on:
            - micro-counter-api
    micro-counter-api:
        build: ./MicroCounter.Api
        depends_on:
            - micro-counter-count-store
    micro-counter-count-store:
        image: "redis:alpine"
